name: funny_webapp_server
description: A server app to monitor when the music will start on the live-stream.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.1.0
  html: ^0.15.4
  shelf_static: ^1.1.2
  mongo_dart: ^0.10.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
